package com.example.locationsearchviewwithretrofit.Model;

import java.util.ArrayList;
import java.util.List;

public class UnitedStates {
    private final State AL;
    private final State AK;
    private final State AZ;
    private final State AR;
    private final State CA;
    private final State CO;
    private final State CT;
    private final State DE;
    private final State FL;
    private final State GA;
    private final State HI;
    private final State ID;
    private final State IL;
    private final State IN;
    private final State IA;
    private final State KS;
    private final State KY;
    private final State LA;
    private final State ME;
    private final State MD;
    private final State MA;
    private final State MI;
    private final State MN;
    private final State MS;
    private final State MO;
    private final State MT;
    private final State NE;
    private final State NV;
    private final State NH;
    private final State NJ;
    private final State NM;
    private final State NY;
    private final State NC;
    private final State ND;
    private final State OH;
    private final State OK;
    private final State OR;
    private final State PA;
    private final State RI;
    private final State SC;
    private final State SD;
    private final State TN;
    private final State TX;
    private final State UT;
    private final State VT;
    private final State VA;
    private final State WA;
    private final State WV;
    private final State WI;
    private final State WY;

    public UnitedStates(State AL, State AK, State AZ, State AR, State CA, State CO, State CT, State DE, State FL, State GA, State HI, State ID, State IL, State IN, State IA, State KS, State KY, State LA, State ME, State MD, State MA, State MI, State MN, State MS, State MO, State MT, State NE, State NV, State NH, State NJ, State NM, State NY, State NC, State ND, State OH, State OK, State OR, State PA, State RI, State SC, State SD, State TN, State TX, State UT, State VT, State VA, State WA, State WV, State WI, State WY) {
        this.AL = AL;
        this.AK = AK;
        this.AZ = AZ;
        this.AR = AR;
        this.CA = CA;
        this.CO = CO;
        this.CT = CT;
        this.DE = DE;
        this.FL = FL;
        this.GA = GA;
        this.HI = HI;
        this.ID = ID;
        this.IL = IL;
        this.IN = IN;
        this.IA = IA;
        this.KS = KS;
        this.KY = KY;
        this.LA = LA;
        this.ME = ME;
        this.MD = MD;
        this.MA = MA;
        this.MI = MI;
        this.MN = MN;
        this.MS = MS;
        this.MO = MO;
        this.MT = MT;
        this.NE = NE;
        this.NV = NV;
        this.NH = NH;
        this.NJ = NJ;
        this.NM = NM;
        this.NY = NY;
        this.NC = NC;
        this.ND = ND;
        this.OH = OH;
        this.OK = OK;
        this.OR = OR;
        this.PA = PA;
        this.RI = RI;
        this.SC = SC;
        this.SD = SD;
        this.TN = TN;
        this.TX = TX;
        this.UT = UT;
        this.VT = VT;
        this.VA = VA;
        this.WA = WA;
        this.WV = WV;
        this.WI = WI;
        this.WY = WY;
    }


    public List<State> getStateList() {
        List<State> stateList = new ArrayList<>();

        stateList.add(AL);
        stateList.add(AK);
        stateList.add(AZ);
        stateList.add(AR);
        stateList.add(CA);
        stateList.add(CO);
        stateList.add(CT);
        stateList.add(DE);
        stateList.add(FL);
        stateList.add(GA);
        stateList.add(HI);
        stateList.add(ID);
        stateList.add(IL);
        stateList.add(IN);
        stateList.add(IA);
        stateList.add(KS);
        stateList.add(KY);
        stateList.add(LA);
        stateList.add(ME);
        stateList.add(MD);
        stateList.add(MA);
        stateList.add(MI);
        stateList.add(MN);
        stateList.add(MS);
        stateList.add(MO);
        stateList.add(MT);
        stateList.add(NE);
        stateList.add(NV);
        stateList.add(NH);
        stateList.add(NJ);
        stateList.add(NM);
        stateList.add(NY);
        stateList.add(NC);
        stateList.add(ND);
        stateList.add(OH);
        stateList.add(OK);
        stateList.add(OR);
        stateList.add(PA);
        stateList.add(RI);
        stateList.add(SC);
        stateList.add(SD);
        stateList.add(TN);
        stateList.add(TX);
        stateList.add(UT);
        stateList.add(VT);
        stateList.add(VA);
        stateList.add(WA);
        stateList.add(WV);
        stateList.add(WI);
        stateList.add(WY);

        return stateList;
    }
}